#!/bin/bash
# Do Kivy stuff

function cd_project {
    cd /home/krister/Dropbox/Projects/Moodle/
}

function cd_git {
    cd /home/krister/ProjectsBIG/moodle/
}

function cd_dev1_parts {
    cd /home/krister/ProjectsBIG/MoodleParts/
}

function connect_vpn {
    cd /home/krister/Dropbox/Projects/Moodle/forticlientsslvpn/
    sudo -b ./forticlientsslvpn
}

function create_routes {
    sudo route add 192.168.249.136 gw 10.212.134.200 ppp0
    sudo route add dev1.moodle.e-ope.ee gw 10.212.134.200 ppp0
    sudo route add 192.168.249.138 gw 10.212.134.200 ppp0
    sudo route add 192.168.249.143 gw 10.212.134.200 ppp0
    sudo route add 192.168.249.147 gw 10.212.134.200 ppp0
    sudo route add 192.168.249.140 gw 10.212.134.200 ppp0
    sudo route add 192.168.249.145 gw 10.212.134.200 ppp0
    sudo route add 192.168.249.136 gw 10.212.134.201 ppp0
    sudo route add dev1.moodle.e-ope.ee gw 10.212.134.201 ppp0
    sudo route add 192.168.249.138 gw 10.212.134.201 ppp0
    sudo route add 192.168.249.143 gw 10.212.134.201 ppp0
    sudo route add 192.168.249.147 gw 10.212.134.201 ppp0
    sudo route add 192.168.249.140 gw 10.212.134.201 ppp0
    sudo route add 192.168.249.145 gw 10.212.134.201 ppp0
    sudo route add 192.168.249.136 gw 10.212.134.202 ppp0
    sudo route add dev1.moodle.e-ope.ee gw 10.212.134.202 ppp0
    sudo route add 192.168.249.138 gw 10.212.134.202 ppp0
    sudo route add 192.168.249.143 gw 10.212.134.202 ppp0
    sudo route add 192.168.249.147 gw 10.212.134.202 ppp0
    sudo route add 192.168.249.140 gw 10.212.134.202 ppp0
    sudo route add 192.168.249.145 gw 10.212.134.202 ppp0
    sudo route add 192.168.249.136 gw 10.212.134.203 ppp0
    sudo route add dev1.moodle.e-ope.ee gw 10.212.134.203 ppp0
    sudo route add 192.168.249.138 gw 10.212.134.203 ppp0
    sudo route add 192.168.249.143 gw 10.212.134.203 ppp0
    sudo route add 192.168.249.147 gw 10.212.134.203 ppp0
    sudo route add 192.168.249.140 gw 10.212.134.203 ppp0
    sudo route add 192.168.249.145 gw 10.212.134.203 ppp0
    sudo route add 192.168.249.136 gw 10.212.134.204 ppp0
    sudo route add dev1.moodle.e-ope.ee gw 10.212.134.204 ppp0
    sudo route add 192.168.249.138 gw 10.212.134.204 ppp0
    sudo route add 192.168.249.143 gw 10.212.134.204 ppp0
    sudo route add 192.168.249.147 gw 10.212.134.204 ppp0
    sudo route add 192.168.249.140 gw 10.212.134.204 ppp0
    sudo route add 192.168.249.145 gw 10.212.134.204 ppp0
}


function connect {
    case $1 in
        h1 ) ssh root@192.168.249.136;;
        krister ) ssh krister@192.168.249.136;;
        git ) ssh root@192.168.249.147;;
        h1mysql ) ssh -t krister@192.168.249.145 "cd /var/lib/mysql; bash";;
        live ) connect_live;;
    esac
}

function connect_live {
    gnome-terminal --window-with-profile=live -e "ssh euni@192.168.249.140" &
}

# MAIN
function press_enter {
    echo ""
    #echo -n "Press Enter to continue.."
    #read
    clear
}

clear=True
selection=
until [ "$selection" = "0" ]; do
    if [ $clear = True ]; then
        clear
    fi
    echo "      "
    echo "      "
    echo "        MOODLE COMMANDS  "
    echo "      -------------------"
    echo "      "
    echo "      1. connect VPN"
    echo "      2. create routes"
    echo "      "
    echo "      3. connect to H1"
    echo "      4. connect to Git"
    echo "      5. connect to h1MySQL"
    echo "      "
    echo "      7. connect to Live"
    echo "      "
    echo "      0. exit"
    echo "      "
    echo -n "      "
    read selection
    echo ""
    case $selection in
        1 ) connect_vpn ;;
        2 ) create_routes ;;
        3 ) clear; connect h1; exit ;;
        4 ) clear; connect git; exit ;;
        5 ) clear; connect h1mysql; exit ;;
        7 ) clear; connect live; exit ;;
        0 ) clear; exit ;;
        * ) echo "Please enter a number"; press_enter
    esac
done
