#!/bin/bash
dir=$(dirname $0)

function start_menu {
    clear
    until [ "$selection" = "0" ]; do
        echo "      "
        echo "      "
        echo "        KUTI COMMANDS  "
        echo "      -----------------"
        echo "      "
        echo "      1. General"
        echo "      3."
        echo "      4. Pilv"
        echo "      5. Screencast"
        echo "      "
        echo "      0. exit"
        echo "      "
        echo -n "   "
        read selection
        echo ""
        case $selection in
            1 ) $dir/kuti_general; exit ;;
            4 ) $dir/kuti_pilv; exit ;;
            5 ) $dir/kuti_screencast; exit ;;
            0 ) clear; exit ;;
            * ) clear
        esac
    done
}

